feat(message): support multiple channel IDs
slackapi/slack-github-action pull request #126
Opened 2022-09-13 17:50 UTC by treemmett

###  Summary

Adds support for comma-separated channel ID's.

Closes #118 

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

2022-09-13 17:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/slackapi/slack-github-action?pullRequest=126) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/slackapi/slack-github-action?pullRequest=126) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/slackapi/slack-github-action?pullRequest=126) it.</sub>

2022-09-13 17:54 UTC, treemmett commented on README.md
> +Multiple channels can be sent the same message by providing a comma-separated list of ID's:
Any thoughts on how to reword this?

2022-09-13 18:03 UTC, filmaj requested changes
Thanks a lot for the PR @treemmett !

I left a couple of comments, one suggestion on how to integrate the new feature you are adding support for in the README and another one regarding test organization.

Going to approve the github action execution - feel free to at-mention me directly if you'd like for me to take another look!

2022-09-13 18:03 UTC, filmaj commented on README.md
> +Multiple channels can be sent the same message by providing a comma-separated list of ID's:
I think I would actually remove this additional section and just add a comment in the specific "Usage" sections above where applicable. E.g. line 90-92 above I would add an extra line of comment that is like:

    # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.

2022-09-13 18:03 UTC, filmaj commented on src/slack-send.js
> +            webResponse = await web.chat.update({ ts, channel: channelId.trim(), text: message, ...(payload || {}) });
Nice, good call to trim it here.

2022-09-13 18:03 UTC, filmaj commented on test/slack-send-test.js
> +        fakeCore.getInput.withArgs('channel-id').returns('C123456,C987654');
Thanks for adding the test! Could we actually split this test case up into two test cases? Ideally I'd like separate tests for the single-channel and multi-channel scenarios.

2022-09-13 18:10 UTC, mwbrooks reviewed
Beauty, thanks for the contribution @treemmett!

2022-09-13 18:10 UTC, mwbrooks commented on README.md
> +Multiple channels can be sent the same message by providing a comma-separated list of ID's:
Yep, good suggestion @filmaj! ➕

2022-09-13 18:22 UTC, treemmett commented
@filmaj Thanks for the suggestions! They've been implemented and pushed.

2022-09-13 18:26 UTC, filmaj approved these changes
Awesome! Thanks a ton for putting this together. Gonna let the tests run then will merge in!

2022-09-13 18:29 UTC, merged

2023-12-19 23:38 UTC, amirkarimi commented
@treemmett Thanks for implementing this feature. We're trying to update the messages sent to multiple channels and we get `Error: Error: An API error occurred: message_not_found`. It updates the message in one channel but not in the other one.