Add payload file path to enhance the github action.
slackapi/slack-github-action pull request #44
Opened 2021-12-17 14:28 UTC by umbertix

Increase code coverage.
Updated Readme to have the new input type.
Added example for the new input type usage.

###  Summary

Describe the goal of this PR. Mention any related Issue numbers.

### Requirements (place an `x` in each `[ ]`)

* [x] I've read and understood the [Contributing Guidelines](https://github.com/slackapi/slack-github-action/blob/main/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).

2021-12-17 14:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/slackapi/slack-github-action?pullRequest=44) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/slackapi/slack-github-action?pullRequest=44) before we can accept your contribution.<br/><hr/>**umbert** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/slackapi/slack-github-action?pullRequest=44) it.</sub>

2021-12-21 02:12 UTC, seratch requested changes

2021-12-21 02:12 UTC, seratch commented on .github/resources/payload-notification.json
> +        "text": "A post by Slack Send GitHub Action. Testing Incoming webhooks",
For better e2e testing, can you add a GitHub variable (say, `${{ github.event_name }}`) in this text?

2021-12-21 02:12 UTC, seratch commented on .github/workflows/main.yml
> +        payloadFilePath: ./.github/resources/payload-notification.json
For other properties, we use a different naming rule. Can we change this?
```suggestion
        payload-file-path: ./.github/resources/payload-notification.json
```

2021-12-21 02:12 UTC, seratch commented on README.md
> +    payloadFilePath: "./payload-slack-content.json"
same as above

2021-12-21 02:12 UTC, seratch commented on src/slack-send.js
> +        throw new Error('Need to provide valid payload file path');
Nice way to tell an error! How about being more specific?
```suggestion
        throw new Error(`The payload-file-path may be incorrect. Failed to load the file: ${payloadFilePath}`);
```

2021-12-21 02:12 UTC, seratch commented on src/slack-send.js
> +        throw new Error('Missing input! Message not sent');
Perhaps, we can make the error message more specific:

* if the channel-id is absent, we can say "channel-id is required for running this action"
* if either slack-message or payload is absent while channel-id exists, we can say "either slack-message or payload is required"

2021-12-21 02:12 UTC, seratch commented on test/slack-send-test.js
> +      it('should accept a payloadFilePath and use it\'s content in the message', async () => {
Thanks for adding tests! I won't repeat but consistently renaming `payloadFilePath` would be appreciated.

2022-01-06 08:35 UTC, seratch approved these changes
LGTM; thanks for working on this!

2022-01-06 08:36 UTC, seratch commented
@stevengill If this change looks good to you, you can merge this 👍  (let's use "Squash and merge" to squash the commits into one)

2022-01-10 08:51 UTC, umbertix commented
I don't have enough permissions to merge. I believe you'll have to do the honors.

2022-01-10 09:12 UTC, seratch commented
@umbertix Thanks for being patient here! My last comment was to Steve, another maintainer of this repo. I wanted to have his review before merging this PR.

2022-01-10 22:59 UTC, stevengill approved these changes
Looks Great!!

2022-01-10 22:59 UTC, merged